name: Terraform Simple

on:
  push:
    branches: ["main"]
    paths:
      - "tf-*/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed folder
        id: changed
        run: |
          DIR=$(git diff --name-only HEAD^ HEAD | grep '^tf-' | cut -d'/' -f1 | uniq)
          echo "DIR=$DIR" >> $GITHUB_OUTPUT

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3

      - name: Run Terraform
        run: |
          cd ${{ steps.changed.outputs.DIR }}
          terraform init
          terraform plan
          terraform apply -auto-approve