name: Terraform Monorepo

on:
  push:
    branches: ["main"]
    paths:
      - "tf-*/**"

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - id: changed
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          files: |
            tf-*/**/*.tf

  terraform:
    needs: detect
    if: needs.detect.outputs.dirs != '[]'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ${{ fromJSON(needs.detect.outputs.dirs) }}

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
